Replace `in-addr.arpa` records in `zone` label for `coredns_cache_.*`
giantswarm/kube-prometheus-stack-app pull request #404
Opened 2024-06-25 11:06 UTC by kopiczko

See the slack thread for more details https://gigantic.slack.com/archives/C02GLN41UP2/p1719305781626429

## Regexp test

```go
package main

import (
	"fmt"
	"regexp"
)

const expr = `([^,]*?,?)(?:(?:,?[\d\.]+\.in-addr\.arpa\.)+)+(,?.*)`

var tests = []string{
	`cluster.local.,31.172.in-addr.arpa.,64.100.in-addr.arpa.,65.100.in-addr.arpa.,something.else.`,
	`cluster.local.,31.172.in-addr.arpa.,64.100.in-addr.arpa.,65.100.in-addr.arpa.,66.100.in-addr.arpa.`,
	`cluster.local.,something.else.`,
	`31.172.in-addr.arpa.,64.100.in-addr.arpa.,65.100.in-addr.arpa.,66.100.in-addr.arpa.,something.else.`,
	`31.172.in-addr.arpa.,64.100.in-addr.arpa.,65.100.in-addr.arpa.,66.100.in-addr.arpa.`,
}

func main() {
	re := regexp.MustCompile("^" + expr + "$")

	for _, test := range tests {
		matches := re.FindAllStringSubmatch(test, -1)
		if len(matches) > 1 {
			panic(fmt.Sprintf("found %d matches, wanted max 1", len(matches)))
		}

		fmt.Printf("\nGroups for %q:\n", test)
		if len(matches) == 0 {
			fmt.Printf("\t__ does not match __\n")
			continue
		}
		for i, group := range matches[0][1:] {
			fmt.Printf("\t%d: %s\n", i+1, group)
		}
	}
}
```

```
$ go run test_regexp.go

Groups for "cluster.local.,31.172.in-addr.arpa.,64.100.in-addr.arpa.,65.100.in-addr.arpa.,something.else.":
        1: cluster.local.,
        2: ,something.else.

Groups for "cluster.local.,31.172.in-addr.arpa.,64.100.in-addr.arpa.,65.100.in-addr.arpa.,66.100.in-addr.arpa.":
        1: cluster.local.,
        2: 

Groups for "cluster.local.,something.else.":
        __ does not match __

Groups for "31.172.in-addr.arpa.,64.100.in-addr.arpa.,65.100.in-addr.arpa.,66.100.in-addr.arpa.,something.else.":
        1: 
        2: ,something.else.

Groups for "31.172.in-addr.arpa.,64.100.in-addr.arpa.,65.100.in-addr.arpa.,66.100.in-addr.arpa.":
        1: 
        2: 
```

## On `grizzly`

<img width="916" alt="Screenshot 2024-06-26 at 14 06 30" src="https://github.com/giantswarm/kube-prometheus-stack-app/assets/4608994/c93552c2-cf36-43a1-8516-ec42167d39d8">

2024-06-25 11:10 UTC, QuentinBisson approved these changes

2024-06-25 11:12 UTC, QuentinBisson requested changes
We should use labeldrop instead

2024-06-25 11:15 UTC, QuentinBisson commented on helm/kube-prometheus-stack/values.yaml
> +      - action: LabelDrop
```suggestion
      - action: labeldrop
```

2024-06-26 13:06 UTC, kopiczko commented
Tested on `grizzly`:

<img width="916" alt="Screenshot 2024-06-26 at 14 06 30" src="https://github.com/giantswarm/kube-prometheus-stack-app/assets/4608994/c93552c2-cf36-43a1-8516-ec42167d39d8">

2024-06-26 13:10 UTC, QuentinBisson approved these changes
LGTM

2024-06-26 14:01 UTC, mcharriere approved these changes
lgtm!

2024-06-26 14:44 UTC, merged